from .Piece import Piece


class King(Piece):
    """
    A class to represent a King chess piece: one step in any direction.
    Castling is a rule of the game, not of the piece: it is generated by GameState.
    """

    name = "King"
    short_name = "K"
    directions = [(-1, -1), (-1, 0), (-1, 1), (0, -1), (0, 1), (1, -1), (1, 0), (1, 1)]
    value = 0  # The king is never traded: it has no material value
